### ISSUE TITLE
Conflict with text 2.0 in GHC 9.6.1 prevents use with latest GHC

### ISSUE THREAD

**Issue by liamzee** [cocreature/nanovg-hs#22]
Any idea on whether nanovg will be updated for use with the latest GHC?

**Comment by liamzee** [comment]
Ummm, crap. It looks like nanovg isn't supporting Text 2.0, and earlier versions require 9.2.x (via ghc-prim), meaning that all GHC versions later than 9.2.7 break.

**Comment by cocreature** [comment]
Do you want to make a PR to update it?

**Comment by liamzee** [comment]
I don't feel competent to do it; I'm really a newbie who's more interested in monomer than nanovg / sdl2.

Looks like monomer's maintainer is PR-ing it now.
